# Generated by Django 5.2.9 on 2026-01-09 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ordr_id',
            new_name='order_id',
        ),
    ]
